# shellcheck disable=SC2148
tap "homebrew/bundle"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "mas"
brew "qemu"
brew "shellcheck"
brew "yt-dlp"
cask "adobe-creative-cloud"
cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "coconutbattery"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "jordanbaird-ice"
cask "keyclu"
cask "loupedeck"
cask "logi-options+"
cask "mediainfo"
cask "microsoft-excel"
cask "microsoft-outlook"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "native-access"
cask "postman"
cask "raspberry-pi-imager"
cask "shureplus-motiv"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "vnc-viewer"
cask "windows-app"
cask "wireshark"
cask "xld"
mas "AmorphousDiskMark", id: 1168254295
mas "Apple Configurator", id: 1037126344
mas "Goodnotes", id: 1444383602
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "MenuBar Stats", id: 714196447
mas "Xcode", id: 497799835
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-pull-request-github"
vscode "hediet.vscode-drawio"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mhutchie.git-graph"
vscode "moshfeu.compare-folders"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "pkief.material-icon-theme"
vscode "sohamkamani.code-eol"
vscode "timonwong.shellcheck"
